name: Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    container:
      image: docker.io/library/node:14-alpine

    steps:
      - uses: actions/checkout@v2

      - name: Cache system dependencies
        uses: actions/cache@v2
        with:
          path: /var/cache/apk
          key: cache-${{ runner.os }}-lint-apk-${{ hashFiles('.github/workflows/lint.yml') }}
          restore-keys: |
            cache-${{ runner.os }}-lint-apk-

      - name: Install system dependencies
        run: apk add --update tar git

      - name: Cache Node dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/yarn
          key: cache-${{ runner.os }}-node-${{ hashFiles('**/yarn.lock', '**/package.json') }}
          restore-keys: |
            cache-${{ runner.os }}-node-

      - name: Install Node dependencies
        run: yarn install

      - name: Lint
        run: yarn lint
