name: Node.js CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node:
          - dubnium-alpine3.11
          - erbium-alpine3.12
          - 13.6-alpine3.11
          - 14-alpine3.12
        postgres:
          - ghcr.io/charmander/pg-test-postgres:10
        include:
          - node: 14-alpine3.12
            postgres: ghcr.io/charmander/pg-test-postgres:9.6
          - node: 14-alpine3.12
            postgres: ghcr.io/charmander/pg-test-postgres:9.5
          - node: 14-alpine3.12
            postgres: ghcr.io/charmander/pg-test-postgres:9.4
          - node: 14-alpine3.12
            postgres: ghcr.io/charmander/pg-test-postgres:9.3
          - node: 14-alpine3.12
            postgres: ghcr.io/charmander/pg-test-postgres:9.2

    container:
      image: docker.io/library/node:${{ matrix.node }}

    services:
      db:
        image: ${{ matrix.postgres }}
        env:
          POSTGRES_HOST_AUTH_METHOD: trust

    steps:
      - uses: actions/checkout@v2

      - name: Install system dependencies
        run: |
          apk add --update \
            git make postgresql-client \
            g++ libc-dev postgresql-dev python3

      - name: Install Node dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Create test tables
        run: node packages/pg/script/create-test-tables.js postgresql://postgres@db/

      - name: Test
        run: yarn test
        env:
          CC: clang
          CXX: clang++
          npm_config_clang: 1
          PGHOST: db
          PGUSER: postgres
          PGDATABASE: postgres
